"""Emit scope-frame cases for the JavaScript decoder to read.

Same arrangement as the histogram cases: generated by the Python suite so the
two halves cannot drift apart unnoticed. A frame decoder that disagrees with its
encoder misdraws rather than fails, which is the worst kind of bug for a display
people make decisions from.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import numpy as np

from mdqm.dqm import framing

OUT = Path(__file__).resolve().parent / "js" / "scopeframe-cases.json"


def build_cases() -> list[dict]:
    rng = np.random.default_rng(11)
    cases = []

    # The ordinary case: sixteen channels of 1024 samples, with derived values.
    chans = [{"channel": c, "first_bin": c,
              "samples": rng.integers(-5000, 500, size=1024, dtype=np.int16)}
             for c in range(16)]
    cases.append({
        "name": "16 channels, 1024 samples, derived values",
        "meta": dict(frame_seq=42, run_number=201, event_number=4242,
                     trigger_number=99, trigger_type=1,
                     timestamp_ticks=1234567890123, board_temp_c=59.25,
                     nominal_ps=1000.0, board_id=36, have_widths=True,
                     widths_cached=False, run_active=True),
        "derived": {"rf_phase_deg": 123.456, "s1_amp_v": 0.3712, "amp_ch00": 0.5},
        "channels": chans,
    })

    # An undecodable channel among decodable ones: it must survive, because a
    # panel that vanishes tells nobody the mode was unreadable.
    mixed = [
        {"channel": 0, "first_bin": 0, "samples": np.arange(-8, 8, dtype=np.int16)},
        {"channel": 1, "first_bin": 5, "samples": None, "encoding": 11},
        {"channel": 16, "first_bin": 0, "samples": np.zeros(4, dtype=np.int16)},
    ]
    cases.append({
        "name": "mixed decoded and undecodable channels",
        "meta": dict(frame_seq=1, run_number=0, event_number=7, board_id=37,
                     nominal_ps=1428.0, have_widths=False, widths_cached=True,
                     run_active=False),
        "derived": {},
        "channels": mixed,
    })

    # An odd sample count, to exercise the 8-byte padding between channels.
    odd = [{"channel": c, "first_bin": 0,
            "samples": np.arange(c, c + 3, dtype=np.int16)} for c in range(3)]
    cases.append({
        "name": "odd sample counts (alignment padding)",
        "meta": dict(frame_seq=2, run_number=5, event_number=6, board_id=1),
        "derived": {"one": 1.0},
        "channels": odd,
    })

    out = []
    for c in cases:
        payload = framing.encode_scope_frame(
            c["channels"], derived=c["derived"], **c["meta"])
        out.append({
            "name": c["name"],
            "payload_b64": base64.b64encode(payload).decode(),
            "meta": {k: (float(v) if isinstance(v, float) else v)
                     for k, v in c["meta"].items()},
            "derived": c["derived"],
            "channels": [{
                "channel": int(ch["channel"]),
                "first_bin": int(ch.get("first_bin", 0)),
                "decoded": ch["samples"] is not None,
                "encoding": int(ch.get("encoding", 0)) if ch["samples"] is None else 0,
                "n_samples": 0 if ch["samples"] is None else int(len(ch["samples"])),
                "samples": [] if ch["samples"] is None else [int(x) for x in ch["samples"]],
            } for ch in c["channels"]],
        })
    return out


def test_generate_scopeframe_cases():
    cases = build_cases()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        "_doc": "Generated by tests/generate_scopeframe_cases.py; decoded by "
                "tests/js/scopeframe.test.js.",
        "cases": cases,
    }, indent=1))
    assert len(cases) >= 3


def test_python_decodes_its_own_frames():
    for case in build_cases():
        frame = framing.decode_scope_frame(base64.b64decode(case["payload_b64"]))
        assert len(frame["channels"]) == len(case["channels"]), case["name"]
        assert frame["derived"].keys() == case["derived"].keys(), case["name"]
