"""Write the AD00/AT00/AC00 cases the JavaScript decoder is tested against.

A pytest file that produces a fixture as a side effect, following
``generate_framing_cases.py``: the point is that the bytes the JS suite decodes
are always encoded by *this* repo's Python layout, so the two cannot drift
apart silently. Run the Python suite and the JSON is refreshed; a field that
moves in ``mdqm.dqm.sampic`` fails in ``tests/js/adbank.test.js`` on the next
node run rather than at 3am in front of a plot that draws and is wrong.

The cases are chosen for the edges, not for realism -- the realism is in
``tests/js/ad-event-fixture.json``, which holds real bytes out of run 108.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

from mdqm.dqm import sampic as S

OUT = Path(__file__).resolve().parent / "js" / "adbank-cases.json"


def _hit(**kw):
    base = {"fe_board_index": 0, "hit_number": 0, "channel": 0, "waveform": [],
            "raw_tot_value": 0, "tot_value": S.TOT_ABSENT, "amplitude": 0.0,
            "baseline": 0.0, "peak": 0.0, "time_index": 0.0, "time_instant": 0.0,
            "time_amplitude": 0.0, "first_cell_timestamp": 0.0}
    base.update(kw)
    return base


def _cases():
    yield "one hit, full 64 samples", [
        _hit(channel=5, hit_number=3,
             waveform=[0.7 + 0.001 * i for i in range(S.AD_MAX_SAMPLES)],
             baseline=0.7176, amplitude=-0.1524, peak=0.5653,
             first_cell_timestamp=9430965.3, time_instant=9430971.0),
    ]
    # data_size below kMaxSamples: every hit still carries all 64 slots, and the
    # tail must not reach a plot.
    yield "a short hit, zero-padded to 64", [
        _hit(channel=1, waveform=[0.77, 0.76, 0.42, 0.75], baseline=0.75,
             amplitude=-0.33, peak=0.42),
    ]
    # channel 21 -> chip 1, input 5. The derived fields are computed on encode,
    # so this is the test that the JS reads them rather than recomputing them
    # from its own idea of CHANNELS_PER_SAMPIC.
    yield "a hit on the second SAMPIC chip", [
        _hit(channel=21, waveform=[0.5, 0.4], baseline=0.5, amplitude=-0.1, peak=0.4),
    ]
    yield "several hits, unsorted channels", [
        _hit(channel=9, waveform=[0.1, 0.2]),
        _hit(channel=2, waveform=[0.3]),
        _hit(channel=31, waveform=[0.4, 0.5, 0.6]),
    ]
    yield "no hits at all", []
    # Negative-going pulses are what this detector actually produces; a decoder
    # that assumed positive amplitude would still pass every case above.
    yield "a negative-going pulse with a real ToT", [
        _hit(channel=6, waveform=[0.74, 0.74, 0.60, 0.31, 0.55, 0.73],
             baseline=0.7413, amplitude=-0.4313, peak=0.31, tot_value=2.75,
             raw_tot_value=44, time_index=3.0, time_amplitude=-0.21),
    ]
    # Two boards reporting the same board-local channel. `channel` alone cannot
    # tell them apart, which is the bug global_channel exists to close.
    yield "two boards, same board-local channel", [
        _hit(fe_board_index=0, channel=5, waveform=[0.7] * 4, amplitude=-0.1),
        _hit(fe_board_index=3, channel=5, waveform=[0.7] * 4, amplitude=-0.2),
    ]

def test_generate_adbank_cases():
    cases = []
    for name, hits in _cases():
        payload = S.encode_ad(hits)
        cases.append({
            "name": name,
            "payload_b64": base64.b64encode(payload).decode(),
            "hits": [{k: v for k, v in h.items() if k != "waveform"}
                     | {"waveform": list(h["waveform"])}
                     for h in S.decode_ad(payload)],
        })

    timing = []
    for ts, n in ((9430965, 2), (0, 0), (2 ** 40 + 7, 17)):
        payload = S.encode_at(ts, n)
        timing.append({"payload_b64": base64.b64encode(payload).decode(),
                       "decoded": S.decode_at(payload)})
    # Telemetry filled, which only generated files do. Every field distinct, so
    # a decoder reading them in the wrong order fails instead of matching by
    # coincidence, and one at 2^32-1 to catch a signed read.
    payload = S.encode_at(9430965, 3, 2, **{
        name: (i + 1) * 11 for i, name in enumerate(S.AT_TELEMETRY_FIELDS)})
    timing.append({"payload_b64": base64.b64encode(payload).decode(),
                   "decoded": S.decode_at(payload)})
    payload = S.encode_at(1, 1, 1, sp_total_us_sum=2 ** 32 - 1)
    timing.append({"payload_b64": base64.b64encode(payload).decode(),
                   "decoded": S.decode_at(payload)})

    collector = []
    for args in ((13840, 1, 3, 2, 9, 2, 13),
                 (0, 0, 0, 0, 0, 0, 0),
                 (2 ** 40 + 7, 1, 35, 4294967295, 11, 2, 17)):
        payload = S.encode_ac(*args)
        collector.append({"payload_b64": base64.b64encode(payload).decode(),
                          "decoded": S.decode_ac(payload)})

    OUT.write_text(json.dumps({
        "_doc": ("Generated by tests/generate_adbank_cases.py from "
                 "mdqm.dqm.sampic. Do not edit: re-run the Python suite. Read "
                 "by tests/js/adbank.test.js, so that the Python and JavaScript "
                 "AD00/AT00/AC00 layouts cannot drift apart without a test "
                 "failing."),
        "ad_hit_bytes": S.AD_HIT_BYTES,
        "ad_max_samples": S.AD_MAX_SAMPLES,
        "at_record_bytes": S.AT_RECORD.size,
        "ac_record_bytes": S.AC_RECORD.size,
        "at_telemetry_fields": list(S.AT_TELEMETRY_FIELDS),
        "tot_absent": S.TOT_ABSENT,
        "cases": cases,
        "timing": timing,
        "collector": collector,
    }, indent=1) + "\n")

    assert OUT.exists()
    assert len(cases) == 7
