//
// Our encoder's bytes, decoded by musip's UNMODIFIED decodeHistogram().
//
// A round-trip through our own Python decoder proves only that we are
// self-consistent. This proves the compatibility claim: musip's page could
// point at our analyzer and draw our histograms.
//
// The cases are generated by tests/generate_framing_cases.py, which is run as
// part of the Python suite, so the two halves cannot drift apart silently.
//

const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");

const { decodeHistogram } = require("./vendor/musip-decodeHistogram.js");

const CASES = path.join(__dirname, "framing-cases.json");

test("the generated cases exist", () => {
  assert.ok(fs.existsSync(CASES),
    "run the Python suite first: it generates tests/js/framing-cases.json");
});

const cases = fs.existsSync(CASES)
  ? JSON.parse(fs.readFileSync(CASES, "utf8")).cases
  : [];

for (const c of cases) {
  test(`musip's decoder reads our ${c.name}`, () => {
    const buf = Buffer.from(c.payload_b64, "base64");
    // A fresh ArrayBuffer starting at 0, which is what the page has after it
    // slices the 8-byte envelope off -- and what the alignment is relative to.
    const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);

    const h = decodeHistogram(ab);

    assert.deepStrictEqual(h.numberOfBins, c.n_bins, "bin counts");
    assert.deepStrictEqual(h.lowEdge, c.low_edge, "low edges");
    assert.deepStrictEqual(h.highEdge, c.high_edge, "high edges");
    assert.strictEqual(Number(h.entries), c.entries, "entry count");
    assert.strictEqual(h.data.constructor.name, c.array_type,
      "the bin content type must survive");
    assert.deepStrictEqual(Array.from(h.data), c.counts_flat,
      "bin contents, under/overflow included and in x-fastest order");
  });
}

test("every case actually ran", () => {
  assert.ok(cases.length >= 4, `only ${cases.length} cases were generated`);
});
